// 30 x 3, 12 bytes
// Pixel format: MONO_HMSB
// Generated by img2lcd.com
int NUMBERS_WIDTH = 30;
int NUMBERS_HEIGHT = 3;
int NUMBER_WIDTH = 3;
int NUMBER_HEIGHT = 3;
const unsigned char numbers_image[] = {
  0xff, 0xff, 0xff, 0xfc, 0xff, 0xff, 0xff, 0xfc, 0xff, 0xff, 0xff, 0xfc,
};
